name: Clang format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Python UTF-8 encoding
      run: export PYTHONIOENCODING=utf-8

    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        exclude: './lib'
        extensions: 'h,cpp,c'
        clangFormatVersion: 16
        inplace: True
      env:
        PYTHONIOENCODING: utf-8

    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
