name: Clang format

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        exclude: './third_party ./external ./common/RFID/API ./PAC/common/prj_mngr'
        extensions: 'h,cpp'
        clangFormatVersion: 17
        style: google
        inplace: True
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
