name: Clang format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Python UTF-8 encoding
      run: export PYTHONIOENCODING=utf-8

    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        exclude: './third_party ./external'
        extensions: 'h,cpp'
        clangFormatVersion: 17
        style: google
        inplace: True
      env:
        PYTHONIOENCODING: utf-8

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
