name: Clang format

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Run Clang-Format
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        exclude: './third_party ./external ./common/RFID/API'
        extensions: 'h,cpp'
        clangFormatVersion: 17
        style: google
        inplace: True

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
